version: 2
jobs:
  security-checks:
    working_directory: ~/repo
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: sh ci/security-checks.sh
      - store_artifacts:
          path: /tmp/artifacts/hawkeye_report.json
  build:
    docker:
      - image: docker:stable
    steps:
      - run:
          command: echo "here goes your build steps"

  tests:
    docker:
      - image: docker:stable
    steps:
      - run:
          command: echo "here goes your tests steps"

  deploy:
    working_directory: ~/repo
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - run:
          command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/master

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - security-checks
      - build:
          requires:
            - security-checks
      - tests:
          requires:
            - build
      - deploy:
          type: approval
          requires:
            - tests
          filters:
            branches:
              only: master
